### PR TITLE
v1.5.0 cleaned up code, improved pausing,

### PR DESCRIPTION
**Pull request by Zarklord**
all shards pause when paused.
clients properly pause when the game pauses.
now uses gem core to facilitate shard communications.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
what is gem core? is that some new backend in the game? or did you have to hunt it down?

I assume you have tested this?
Kinda hard, but yeah.

Are you able to upload this?

**Comment by Zarklord** [comment]
Gem Core is a backend I created, that can do lots of cool and powerful things, like sending messages between shards.
yes, this is fully tested and stable.
I could "reupload" this where Im the main creator(if you prefer), but in order to update the existing workshop file, you would need to do that.

**Comment by hmaarrfk** [comment]
Is there a permission i could give you to enable you to upload it? I thought some users mentionned that you should be credited more and that I had enabled some extra permissions for you

**Comment by Zarklord** [comment]
sadly not, steam has dropped the ball hard in terms of the workshop system and being able to update the mod even if you werent the original uploader.

**Comment by hmaarrfk** [comment]
I don't even remember how to upload it, and removed steam from my computer..... so any ideas?

seems like a waste to remove all the history from that mod

**Comment by Zarklord** [comment]
Hmm, the only option would be you installing steam and the don't starve together mod tools, and uploading the update, otherwise were stuck at me re-uploading the mod(which I would prefer to also not do, as your mod has a giant subscriber base, which would be a shame to get rid of.)

**Comment by Zarklord** [comment]
have you decided if your gonna get steam and update it, or if you want me to upload a new version?

**Comment by hmaarrfk** [comment]
I think I published it. Let me know.

**Comment by hmaarrfk** [comment]
Can you check fi you can upload the package now? I think  Ihad to agree to some new terms. I have done that now. Hopefully that allows you to upload the package on your own schedule!

**Comment by Zarklord** [comment]
👍

**Pull request merged**
