### PR TITLE
fixed pausescreen pausing.

### PR DESCRIPTION
**Pull request by Zarklord**
this allows you to toggle pausing from the esc menu like before.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Can you explain what you did? Did you simply move the script? Do I have to take off the other file?

**Comment by Zarklord** [comment]
well when they did the GUI overhaul they made a new pausescreen in screens/redux/pausescreen.h, in addition to it being in a different location, they did change the code a bit and I adapted it the new pausescreen code. if you accept the pull request the mod is in full working order with no extra changes needing to be done to it.

**Comment by hmaarrfk** [comment]
Cool.

So it seems that maybe you can delete the old file? Or do you want to keep it there in case somebody doesn't update their game?

**Comment by Zarklord** [comment]
i left it for legacy reason's, though it could be removed(as far as im aware)...

**Comment by hmaarrfk** [comment]
Thanks, I just pulled this and updated the version number in a few other locations. You have been credited too. Please use an other pull request if you feel like being credited some other way.

**Pull request merged**
