### PR TITLE
v1.5.1 Add Chinese translations

### PR DESCRIPTION
**Pull request by cometeme**
Hi, there. Global Pause mod is very helpful! Thanks for your work!
I made a small update on localization, and I hope this will help others use this mod better :P

## Updates:
- Add Chinese translations to the mod.
- Also create a Chinese mod introduction.
- Add a "Language" option, and make it easier for other people to translate this mod.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I can merge this, but I don't even have steam to upload things

**Comment by cometeme** [comment]
That's ok, you can upload it to steam when you have free time 😊.

**Comment by hmaarrfk** [comment]
@Zarklord you still maintaining this?

**Comment by Zarklord** [comment]
I am, I even have a way (due to the fact that it uses Gem Core) to release patches for it, that everyone automatically gets, so I can take a look at merging this.

**Comment by hmaarrfk** [comment]
What does that mean? you don't need to go through the standard steam process? GemCore can sideload lua files?

**Comment by Zarklord** [comment]
It just means since this requires another mod, I can apply patches to things and bugs I find, by doing something inside Gem Core, I made a patch that also mutes sounds when paused, along with fixing a bug with pausing and c_spawn()ing players in, I can do something similiar with this.

**Comment by hmaarrfk** [comment]
We were never able to get you authorization to upload the mod yourself right?

**Comment by Zarklord** [comment]
correct, this is the next best alternative though.

**Comment by hmaarrfk** [comment]
to jsut fold things into your mega gemcore package?

**Pull request closed without merging**
